# Generated by Django 3.2.25 on 2024-04-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='ProductCode',
            new_name='DiseaseName',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProductName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='gst',
        ),
    ]
