# Generated by Django 3.2.25 on 2024-04-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20240430_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='patiance',
        ),
    ]
